const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SYNAPSE_TEST_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
const errors=[];const mm=await browser.newPage({viewport:{width:1100,height:800}}),rm=await browser.newPage({viewport:{width:1100,height:800}});for(const p of [mm,rm])p.on('pageerror',e=>errors.push(e.message));
await mm.addInitScript(()=>{if(window===top)localStorage.setItem('mindmaps',JSON.stringify({test:{name:'Test map',nodes:[{id:1,text:'Topic',parent:null,x:350,y:200,width:160,height:80}]}}))});
await mm.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await rm.goto(pathToFileURL(path.resolve(__dirname,'../web_roadmap/index.html')).href);await mm.waitForSelector('#mindmap-select-btn');await mm.locator('#mindmap-loading-overlay').waitFor({state:'hidden'});
const geometry=async(p,s)=>p.locator(s).evaluate(e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e);return {x:r.x,y:r.y,w:r.width,h:r.height,radius:c.borderRadius,font:c.fontSize,bg:c.backgroundColor}});
for(const width of [1100,390]){for(const p of [mm,rm])await p.setViewportSize({width,height:800});for(const [a,b]of [['#zoom-in-btn','#zoom-in'],['#zoom-out-btn','#zoom-out'],['#fit-map-btn','#fit'],['#undo-btn','#undo'],['#redo-btn','#redo'],['#center-view-btn','#center'],['#new-map-btn','#new-map'],['#hamburger-btn','#document-menu > summary']]){const first=await geometry(mm,a),second=await geometry(rm,b);if(a.includes('new-map')){delete first.x;delete second.x}assert.deepEqual(second,first,a+' and '+b+' at '+width)}assert.equal(await rm.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
for(const p of [mm,rm])await p.setViewportSize({width:1100,height:800});
// A single grid implementation produces identical dots for matching views, in both themes.
for(const dark of [false,true]){const styles=[];for(const [p,id]of [[mm,'mindmap-container'],[rm,'workspace']])styles.push(await p.evaluate(async({id,dark})=>{document.documentElement.classList.toggle('dark',dark);const el=document.getElementById(id);await new Promise(resolve=>setTimeout(resolve,350));window.__workspaceGrid(el,{x:31,y:-17,scale:.4});const c=getComputedStyle(el);return[c.backgroundColor,c.backgroundImage,c.backgroundSize,c.backgroundPosition]},{id,dark}));assert.deepEqual(styles[0],styles[1]);}for(const p of [mm,rm])await p.evaluate(()=>document.documentElement.classList.remove('dark'));
assert.equal(await rm.locator('[data-mode=auto]').getAttribute('aria-pressed'),'true');assert.equal(await rm.locator('[data-mode=hand] svg').count(),1);
const state=()=>rm.evaluate(()=>window.__roadmapSnapshot().data.maps[0]);
const drag=async(x,y,dx,dy)=>{await rm.mouse.move(x,y);await rm.mouse.down();await rm.mouse.move(x+dx,y+dy,{steps:8});await rm.mouse.up()};
let r=await rm.locator('#scene').boundingBox();let before=await state();await drag(r.x+700,r.y+400,70,40);let after=await state();assert.equal(after.view.x-before.view.x,70);assert.equal(after.view.y-before.view.y,40);
await rm.locator('#add-menu summary').click();await rm.locator('[data-shape=rect]').click();assert.equal(await rm.locator('[data-mode=auto]').getAttribute('aria-pressed'),'true');r=await rm.locator('#objects > g').boundingBox();before=await state();await drag(r.x+r.width/2,r.y+r.height/2,80,30);after=await state();assert.equal(after.objects[0].x-before.objects[0].x,80);assert.equal(after.view.x,before.view.x);
// Auto mode also selects and moves a free arrow without moving the viewport.
await rm.locator('#add-menu summary').click();await rm.locator('[data-mode=arrow]').click();
r=await rm.locator('#scene').boundingBox();await drag(r.x+250,r.y+360,180,0);await rm.locator('[data-mode=auto]').click();
const midpoint=await rm.locator('[data-arrow]').evaluate(p=>{const q=p.getPointAtLength(p.getTotalLength()/2).matrixTransform(p.getScreenCTM());return{x:q.x,y:q.y}});
before=await state();await drag(midpoint.x,midpoint.y,35,20);after=await state();const arrowBefore=before.objects.find(o=>o.kind==='arrow'),arrowAfter=after.objects.find(o=>o.kind==='arrow');assert.equal(arrowAfter.a.x-arrowBefore.a.x,35);assert.equal(arrowAfter.b.y-arrowBefore.b.y,20);assert.deepEqual(after.view,before.view);
await rm.locator('#scene').click({position:{x:800,y:550}});assert.equal(await rm.locator('#selection > *').count(),0);
// Explicit hand mode pans even over a shape; explicit select mode selects a region.
await rm.locator('[data-mode=hand]').click();r=await rm.locator('#objects > g').first().boundingBox();before=await state();await drag(r.x+r.width/2,r.y+r.height/2,40,20);after=await state();assert.equal(after.objects[0].x,before.objects[0].x);assert.equal(after.view.x-before.view.x,40);
await rm.locator('[data-mode=select]').click();before=await state();r=await rm.locator('#scene').boundingBox();await drag(r.x+750,r.y+430,50,40);assert.deepEqual((await state()).view,before.view);
await rm.locator('[data-mode=auto]').click();await rm.reload();await rm.waitForSelector('[data-mode=auto][aria-pressed=true]');
// Shared listbox and menus remain operable.
await mm.locator('#mindmap-select-btn').click();assert.equal(await mm.getByRole('option').count(),1);await mm.getByRole('option').click();await rm.locator('#map-select-btn').click();await rm.getByRole('option').click();
await mm.locator('#node-1 .node-textarea').fill('Saved topic');await mm.waitForFunction(()=>document.querySelector('#mindmap-save-status').dataset.state==='saved');assert.match(await mm.locator('#mindmap-save-status').innerText(),/Gespeichert|Saved/);
await rm.locator('#add-menu summary').click();await rm.locator('[data-shape=rect]').click();await rm.locator('#scene').click({position:{x:850,y:450}});await mm.locator('#center-view-btn').click();await mm.locator('#hamburger-btn').click();await rm.locator('#document-menu summary').click();
for(const [p,name]of [[mm,'mindmap'],[rm,'roadmap']]){await p.bringToFront();await p.waitForTimeout(400);await p.screenshot({path:path.resolve(__dirname,`../docs/${name}-ui-aligned.png`)});await p.setViewportSize({width:390,height:800});await p.bringToFront();await p.waitForTimeout(400);await p.screenshot({path:path.resolve(__dirname,`../docs/${name}-ui-aligned-narrow.png`)});}
// Failed writes must not leave a misleading Saved status.
await mm.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('test','QuotaExceededError')};__synapseFlushMindmap()});assert.equal(await mm.locator('#mindmap-save-status').getAttribute('data-state'),'error');
assert.deepEqual(errors,[]);console.log('PASS shared geometry at 1100/390px, identical grid light/dark, auto pan/object drag, manual overrides, default reset, listboxes, truthful save status');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
