const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const {pathToFileURL}=require('node:url');
const shape=(id,x,y,html='',extra={})=>({id,kind:'shape',shape:'rect',x,y,w:180,h:90,rotation:0,html,fontSize:20,fill:'#ffffff',stroke:'#252525',...extra});
const arrow=(id,a,b,extra={})=>({id,kind:'arrow',a,b,route:'rounded',stroke:'#252525',tip:'triangle',dash:'solid',label:'',labelSize:14,...extra});
const collection=objects=>({version:1,active:'test',maps:[{id:'test',name:'Lernweg',objects,view:{x:100,y:70,scale:1}}]});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SYNAPSE_TEST_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const url=pathToFileURL(path.resolve(__dirname,'../web_roadmap/index.html')).href;const timings=[];
for(const count of [100,500,1000]){const page=await browser.newPage({viewport:{width:1200,height:850}});const objects=[];for(let i=0;i<count;i++)objects.push(shape('n'+i,(i%25)*220,Math.floor(i/25)*130,'Thema '+i));for(let i=1;i<count;i++)objects.push(arrow('e'+i,{node:'n'+(i-1),side:'right'},{node:'n'+i,side:'left'}));await page.addInitScript(d=>window.__ROADMAP_DATA__=d,collection(objects));const start=Date.now();await page.goto(url);await page.waitForFunction(()=>window.__roadmapSnapshot);const load=Date.now()-start;const elapsed=await page.evaluate(async()=>{const start=performance.now();document.querySelector('#zoom-in').click();await new Promise(requestAnimationFrame);return performance.now()-start});const bytes=await page.evaluate(()=>new Blob([JSON.stringify(window.__roadmapSnapshot().data)]).size);timings.push({shapes:count,arrows:count-1,loadMs:load,zoomMs:Math.round(elapsed),jsonBytes:bytes});assert.equal(await page.locator('#objects > g').count(),2*count-1);await page.close()}
console.log('SCALE',JSON.stringify(timings));
const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const example=collection([shape('main',90,280,'<b>Test Box</b>',{w:280,h:140,fill:'#f2faff',stroke:'#429bea',fontSize:30}),shape('upper',330,0,'<b>Box 2</b>',{w:190,h:90,fontSize:28}),shape('separate',660,155,'Separate<br>Beispielbox',{w:135,h:135,fontSize:18}),arrow('up',{node:'main',side:'top'},{node:'upper',side:'bottom'}),arrow('right',{node:'main',side:'right'},{x:850,y:490}),arrow('bottom',{node:'main',side:'bottom'},{x:20,y:610},{label:'Pfeil Text im Textfeld',labelSize:17}),arrow('other',{node:'separate',side:'right'},{x:1030,y:655})]);await page.addInitScript(d=>window.__ROADMAP_DATA__=d,example);await page.goto(url);await page.locator('#fit').click();await page.screenshot({path:path.resolve(__dirname,'../docs/roadmap-preview-wide.png')});
// Import sanitization + full data preservation when visual text is truncated.
const bad=collection([shape('safe',0,0,'<img src=x onerror="window.PWNED=1"><b>Keep me</b><script>window.PWNED=1</script>')]);await page.locator('#import-file').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.waitForFunction(()=>document.querySelector('#map-select').options.length===2);assert.equal(await page.evaluate(()=>window.PWNED),undefined);assert.equal(await page.locator('#objects img,#objects script').count(),0);assert.match(await page.locator('#objects').textContent(),/Keep me/);
// Text selection formatting does not become object deletion/clipboard actions.
await page.locator('#objects > g').dblclick();const editor=page.locator('[contenteditable=true]');await editor.fill('Formatted text');await editor.selectText();await page.locator('[data-format=italic]').click();await page.locator('#text-size').fill('26');await page.locator('#text-size').press('Tab');await page.locator('#text-done').click();const saved=await page.evaluate(()=>window.__roadmapSnapshot().data);assert.match(saved.maps.find(m=>m.id===saved.active).objects[0].html,/italic|<i>/);assert.match(saved.maps.find(m=>m.id===saved.active).objects[0].html,/26px/);
// Imported invalid identifiers cannot become CSS selectors or overwrite current maps.
const invalid=collection([shape('bad"id',0,0)]);await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForTimeout(100);assert.equal(await page.locator('#map-select option').count(),2);
assert.deepEqual(errors,[]);console.log('PASS: synthetic 100/500/1000-shape scenes, rich text formatting, sanitized import, invalid IDs');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
